CREATE TABLE HEROI
(
    CODIGO     NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOME       VARCHAR(50) NOT NULL,
    OUTRO_NOME VARCHAR(50),
    LEVEL      NUMBER(11)  NOT NULL,
    IMAGEM     VARCHAR,
    PODERES    VARCHAR,
    CONSTRAINT CODIGO_HEROI_PK PRIMARY KEY (CODIGO)
);