CREATE TABLE LUTA
(
    CODIGO          NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LUTA_DATA       VARCHAR NOT NULL,
    NOME_VENCEDOR   VARCHAR NOT NULL,
    LEVEL_VENCEDOR  VARCHAR NOT NULL,
    IMAGEM_VENCEDOR VARCHAR NOT NULL,
    NOME_PERDEDOR   VARCHAR NOT NULL,
    LEVEL_PERDEDOR  VARCHAR NOT NULL,
    IMAGEM_PERDEDOR VARCHAR NOT NULL,
    TIME_VENCEDOR   VARCHAR NOT NULL,
    TIME_PERDEDOR   VARCHAR NOT NULL,
    CONSTRAINT CODIGO_LUTA_PK PRIMARY KEY (CODIGO)
);